#include "codegen.h"

#include <stdio.h>

// ビルド時に Makefile が -DMYTHON_TARGET_TRIPLE=... で渡してきます。
// 万一渡されなかった場合でも動くようにフォールバックを置いておく。
#ifndef MYTHON_TARGET_TRIPLE
#define MYTHON_TARGET_TRIPLE ""
#endif

// ── 出力バッファ ────────────────────────────────────────────
// IR は「後から前に戻って書き足したい」ことがあるため、
// 用途別のバッファに分けて最後に連結します。
// 例：関数本体の生成中に文字列リテラルを見つけたら globals に追記する。
typedef struct {
    StrBuf header;   // source_filename, target triple, 型定義
    StrBuf globals;  // グローバル変数・文字列定数
    StrBuf decls;    // declare（外部関数宣言）
    StrBuf body;     // 関数定義

    int tmp_counter;  // 一時値 %tN の連番（関数ごとにリセットする）
} Emitter;

// 新しい一時値の名前を返す（"%t0", "%t1", ...）
//
// ⚠️ 規約 R4：必ず英字始まりの名前にします。
//    %0 のような数値名を自分で使うと、LLVM の暗黙採番と衝突して
//    "instruction expected to be numbered '%N'" という分かりにくい
//    エラーになります。
static char *new_tmp(Emitter *e) {
    char *buf = xmalloc(24);
    snprintf(buf, 24, "%%t%d", e->tmp_counter++);
    return buf;
}

// ── 式の生成 ────────────────────────────────────────────────
//
// gen_expr の約束：
//   「式を評価する命令列を body に出力し、
//     結果の値が入っている場所の名前（レジスタ名 or 即値）を返す」
//
// この 1 つの約束が、コード生成器の設計全体を決めます。
static char *gen_expr(Emitter *e, Node *n) {
    switch (n->kind) {
        case ND_INT: {
            // 整数リテラルは命令を出す必要すらありません。
            // LLVM は即値をオペランドに直接書けるので（add i64 42, 1）、
            // 「42」という文字列をそのまま返します。
            char *buf = xmalloc(24);
            snprintf(buf, 24, "%lld", n->ival);
            return buf;
        }
        default:
            UNREACHABLE();
    }
}

// ── 関数の生成 ──────────────────────────────────────────────

// ユーザーのプログラム本体を @mython_main として出力する。
//
// 第1章ではプログラム全体がただ 1 つの式なので、
// 「その式を評価して返すだけの関数」になります。
static void gen_mython_main(Emitter *e, Node *ast) {
    e->tmp_counter = 0;  // 関数ごとに一時値の連番をリセット（規約）

    sb_printf(&e->body, "define i64 @mython_main() {\n");
    sb_printf(&e->body, "entry:\n");

    char *val = gen_expr(e, ast);
    sb_printf(&e->body, "  ret i64 %s\n", val);

    sb_printf(&e->body, "}\n");
}

// C の main を出力する。
//
// Mython の main は int（= i64）を返しますが、C の main は i32 を返します。
// そこで「ユーザーの main を @mython_main として出し、@main は
// それを呼んで trunc するラッパにする」方式をとります。
// （ir-conventions.md 第7節の方式 A）
//
// 🤔 なぜラッパ方式か：main を他の関数と同じ規則で生成できるので、
//    コード生成器に「main だけ特別」という分岐が入りません。
static void gen_c_main(Emitter *e) {
    e->tmp_counter = 0;

    sb_printf(&e->body, "\n");
    sb_printf(&e->body, "define i32 @main() {\n");
    sb_printf(&e->body, "entry:\n");

    char *t0 = new_tmp(e);
    sb_printf(&e->body, "  %s = call i64 @mython_main()\n", t0);

    char *t1 = new_tmp(e);
    sb_printf(&e->body, "  %s = trunc i64 %s to i32\n", t1, t0);

    sb_printf(&e->body, "  ret i32 %s\n", t1);
    sb_printf(&e->body, "}\n");
}

// ── 入口 ───────────────────────────────────────────────────

char *codegen(Node *ast, const char *source_name) {
    Emitter e = {0};
    sb_init(&e.header);
    sb_init(&e.globals);
    sb_init(&e.decls);
    sb_init(&e.body);

    // ① ヘッダ
    sb_printf(&e.header, "; Generated by mythonc\n");
    sb_printf(&e.header, "source_filename = \"%s\"\n", source_name);

    // ⚠️ 規約 R11：target triple は必ず出力する。
    //    書かないと clang が -Woverride-module 警告を出します。
    if (MYTHON_TARGET_TRIPLE[0])
        sb_printf(&e.header, "target triple = \"%s\"\n", MYTHON_TARGET_TRIPLE);

    // ⑤ 関数定義
    sb_printf(&e.body, "\n");
    gen_mython_main(&e, ast);
    gen_c_main(&e);

    // 4 つのバッファを規定の順に連結する
    StrBuf out;
    sb_init(&out);
    sb_printf(&out, "%s", sb_str(&e.header));
    sb_printf(&out, "%s", sb_str(&e.globals));
    sb_printf(&out, "%s", sb_str(&e.decls));
    sb_printf(&out, "%s", sb_str(&e.body));
    return sb_str(&out);
}
